/* Spark C-like lift from ALL_SECTIONS.disasm (objdump -D).
 * Produces out/decompile/<name>/lifted/ section .c files.
 * Asm-driven pipeline companion (not a commercial decompiler).
 * Maps each disasm line into C-like statements.
 *
 * Usage:
 *   ./spark-lift OUT_DECOMPILE_DIR
 *     expects OUT_DECOMPILE_DIR/ALL_SECTIONS.disasm
 *     writes OUT_DECOMPILE_DIR/lifted/
 */
#define _GNU_SOURCE
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

static void die(const char *w) {
  fprintf(stderr, "spark-lift: %s: %s\n", w, strerror(errno));
  exit(1);
}

static void sanitize_sec(char *dst, size_t n, const char *src) {
  size_t j = 0;
  for (size_t i = 0; src[i] && j + 1 < n; i++) {
    char c = src[i];
    if (!(isalnum((unsigned char)c) || c == '_' || c == '.'))
      c = '_';
    if (c == '.')
      c = '_';
    dst[j++] = c;
  }
  if (j == 0) {
    snprintf(dst, n, "section");
    return;
  }
  dst[j] = 0;
}

/* Convert one objdump insn line into a C-like comment+stmt. */
static void emit_insn(FILE *out, const char *line) {
  /* typical: "  401000:\t48 89 e5\t\tmov    %rsp,%rbp" */
  const char *colon = strchr(line, ':');
  if (!colon)
    return;
  const char *tab = strchr(colon, '\t');
  if (!tab)
    return;
  const char *mn = tab;
  while (*mn == '\t' || *mn == ' ')
    mn++;
  /* skip hex-bytes field if present */
  int hexish = 1;
  for (const char *p = mn; *p && *p != '\t'; p++) {
    if (!isxdigit((unsigned char)*p) && *p != ' ') {
      hexish = 0;
      break;
    }
  }
  if (hexish) {
    const char *t2 = strchr(mn, '\t');
    if (t2) {
      mn = t2;
      while (*mn == '\t' || *mn == ' ')
        mn++;
    }
  }

  while (*line == ' ')
    line++;
  colon = strchr(line, ':');
  if (!colon)
    return;
  char addr[32];
  size_t alen = (size_t)(colon - line);
  if (alen >= sizeof addr)
    alen = sizeof addr - 1;
  memcpy(addr, line, alen);
  addr[alen] = 0;

  fprintf(out, "    /* %s */ __asm_stmt(\"%s\");\n", addr, mn);
}

int main(int argc, char **argv) {
  if (argc < 2) {
    fputs("Usage: spark-lift OUT_DECOMPILE_DIR\n", stderr);
    return 2;
  }
  const char *dir = argv[1];
  char dis_path[768];
  snprintf(dis_path, sizeof dis_path, "%s/ALL_SECTIONS.disasm", dir);

  FILE *in = fopen(dis_path, "r");
  if (!in) {
    fprintf(stderr, "spark-lift: missing %s — run disasm first\n",
            dis_path);
    return 1;
  }

  char lift_dir[800];
  snprintf(lift_dir, sizeof lift_dir, "%s/lifted", dir);
  mkdir(lift_dir, 0755);

  char line[4096];
  FILE *cur = NULL;
  char cur_sec[256] = "";
  unsigned long long stmts = 0;
  unsigned sections = 0;

  /* preamble index */
  char idx_path[850];
  snprintf(idx_path, sizeof idx_path, "%s/lifted.c", lift_dir);
  FILE *idx = fopen(idx_path, "w");
  if (!idx)
    die("open lifted.c");
  fprintf(idx,
          "/* Spark hardware-level C-like lift from objdump -D.\n"
          " * Not a full decompiler — faithful insn→stmt mapping.\n"
          " * Generated by spark-lift.\n"
          " */\n"
          "#ifndef SPARK_ASM_STMT\n"
          "#define __asm_stmt(S) do { /* S */ } while (0)\n"
          "#endif\n\n");

  while (fgets(line, sizeof line, in)) {
    /* section header: "Disassembly of section .text:" */
    if (strncmp(line, "Disassembly of section ", 23) == 0) {
      if (cur) {
        fprintf(cur, "}\n");
        fclose(cur);
        cur = NULL;
      }
      char *p = line + 23;
      char *end = strchr(p, ':');
      if (end)
        *end = 0;
      sanitize_sec(cur_sec, sizeof cur_sec, p);
      char spath[900];
      snprintf(spath, sizeof spath, "%s/%s.c", lift_dir, cur_sec);
      cur = fopen(spath, "w");
      if (!cur)
        die("open section .c");
      fprintf(cur,
              "/* lifted from section %s */\n"
              "#include \"lifted_common.h\"\n"
              "void spark_section_%s(void) {\n",
              p, cur_sec);
      fprintf(idx, "#include \"%s.c\" /* section %s */\n", cur_sec,
              p);
      sections++;
      continue;
    }
    if (!cur)
      continue;
    /* skip blank / file headers */
    if (line[0] == '\n' || line[0] == 0)
      continue;
    if (strstr(line, "file format"))
      continue;
    /* symbol labels: "0000000000401000 <main>:" */
    if (strchr(line, '<') && strstr(line, ">:")) {
      char *lt = strchr(line, '<');
      char *gt = strchr(lt, '>');
      if (lt && gt) {
        *gt = 0;
        fprintf(cur, "  /* label %s */\n", lt + 1);
      }
      continue;
    }
    if (strchr(line, ':') && strstr(line, "\t")) {
      emit_insn(cur, line);
      stmts++;
    }
  }
  if (cur) {
    fprintf(cur, "}\n");
    fclose(cur);
  }

  /* common header */
  char ch[850];
  snprintf(ch, sizeof ch, "%s/lifted_common.h", lift_dir);
  FILE *hf = fopen(ch, "w");
  if (!hf)
    die("common.h");
  fputs("#pragma once\n"
        "#ifndef SPARK_ASM_STMT\n"
        "#define __asm_stmt(S) do { (void)(S); } while (0)\n"
        "#endif\n",
        hf);
  fclose(hf);

  fprintf(idx,
          "\n/* sections=%u stmts=%llu */\n"
          "int spark_lift_main(void) { return 0; }\n",
          sections, stmts);
  fclose(idx);
  fclose(in);

  printf("{\"op\":\"lift\",\"ok\":true,\"dir\":\"%s/lifted\","
         "\"sections\":%u,\"stmts\":%llu,"
         "\"note\":\"C-like insn mapping from ALL_SECTIONS.disasm\"}\n",
         dir, sections, stmts);
  return 0;
}
